// This file was generated by Rcpp::compileAttributes
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// rcpp_hello_world
List rcpp_hello_world();
RcppExport SEXP marsrover_rcpp_hello_world() {
BEGIN_RCPP
    Rcpp::RNGScope __rngScope;
    List __result = rcpp_hello_world();
    return Rcpp::wrap(__result);
END_RCPP
}
