# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

rcpp_add_biases <- function(m, v) {
    .Call('marsrover_rcpp_add_biases', PACKAGE = 'marsrover', m, v)
}

rectify <- function(m) {
    .Call('marsrover_rectify', PACKAGE = 'marsrover', m)
}

